# Lab | Web Scraping

Welcome to the "Books to Scrape" Web Scraping Adventure Lab!

**Objective**

In this lab, we will embark on a mission to unearth valuable insights from the data available on Books to Scrape, an online platform showcasing a wide variety of books. As data analyst, you have been tasked with scraping a specific subset of book data from Books to Scrape to assist publishing companies in understanding the landscape of highly-rated books across different genres. Your insights will help shape future book marketing strategies and publishing decisions.

**Background**

In a world where data has become the new currency, businesses are leveraging big data to make informed decisions that drive success and profitability. The publishing industry, much like others, utilizes data analytics to understand market trends, reader preferences, and the performance of books based on factors such as genre, author, and ratings. Books to Scrape serves as a rich source of such data, offering detailed information about a diverse range of books, making it an ideal platform for extracting insights to aid in informed decision-making within the literary world.

**Task**

Your task is to create a Python script using BeautifulSoup and pandas to scrape Books to Scrape book data, focusing on book ratings and genres. The script should be able to filter books with ratings above a certain threshold and in specific genres. Additionally, the script should structure the scraped data in a tabular format using pandas for further analysis.

**Expected Outcome**

A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`. The function should scrape book data from the "Books to Scrape" website and return a `pandas` DataFrame with the following columns:

**Expected Outcome**

- A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`.
- The function should return a DataFrame with the following columns:
  - **UPC**: The Universal Product Code (UPC) of the book.
  - **Title**: The title of the book.
  - **Price (£)**: The price of the book in pounds.
  - **Rating**: The rating of the book (1-5 stars).
  - **Genre**: The genre of the book.
  - **Availability**: Whether the book is in stock or not.
  - **Description**: A brief description or product description of the book (if available).
  
You will execute this script to scrape data for books with a minimum rating of `4.0 and above` and a maximum price of `£20`. 

Remember to experiment with different ratings and prices to ensure your code is versatile and can handle various searches effectively!

**Resources**

- [Beautiful Soup Documentation](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)
- [Pandas Documentation](https://pandas.pydata.org/pandas-docs/stable/index.html)
- [Books to Scrape](https://books.toscrape.com/)

**Hint**

Your first mission is to familiarize yourself with the **Books to Scrape** website. Navigate to [Books to Scrape](http://books.toscrape.com/) and explore the available books to understand their layout and structure. 

Next, think about how you can set parameters for your data extraction:

- **Minimum Rating**: Focus on books with a rating of 4.0 and above.
- **Maximum Price**: Filter for books priced up to £20.

After reviewing the site, you can construct a plan for scraping relevant data. Pay attention to the details displayed for each book, including the title, price, rating, and availability. This will help you identify the correct HTML elements to target with your scraping script.

Make sure to build your scraping URL and logic based on the patterns you observe in the HTML structure of the book listings!


---

**Best of luck! Immerse yourself in the world of books, and may the data be with you!**

**Important Note**:

In the fast-changing online world, websites often update and change their structures. When you try this lab, the **Books to Scrape** website might differ from what you expect.

If you encounter issues due to these changes, like new rules or obstacles preventing data extraction, don’t worry! Get creative.

You can choose another website that interests you and is suitable for scraping data. Options like Wikipedia, The New York Times, or even library databases are great alternatives. The main goal remains the same: extract useful data and enhance your web scraping skills while exploring a source of information you enjoy. This is your opportunity to practice and adapt to different web environments!

In [ ]:
# Your solution goes here. UPC/Title/Price/rating/Genre/availability/description; min 4.0 and above mx price 20

#response = requests.get(url_initial)
#response.content
#soup=BeautifulSoup(response.content)
#total_pages = math.ceil(int(soup.find("form", attrs = {"class":"form-horizontal"}).find_all("strong")[0].get_text())/int(soup.find("form", attrs = {"class":"form-horizontal"}).find_all("strong")[2].get_text()))
#total_pages

#product URL
#product_grid = soup.find("div",{"class":"col-sm-8 col-md-9"})
#products = product_grid.find_all("li",{"class":"col-xs-6 col-sm-4 col-md-3 col-lg-3"})
#display(products)[0]
#display(len(products))
#product_url = url_initial+product_grid.find("a")["href"]
#product_url


#UPC
#response2 = requests.get(product_url)
#response2.content
#soup2=BeautifulSoup(response2.content)
#soup2
#upc = soup2.find("table", {"class":"table table-striped"}).find("tr").find("td").get_text()
#display(upc)

#title
#itle = soup.find("li",attrs={"class":"col-xs-6 col-sm-4 col-md-3 col-lg-3"}).find_all("a")[1].get_text()
#title


#price

#price = float(soup.find("div",attrs={"class":"product_price"}).find("p",attrs={"class":"price_color"}).get_text().replace("£",""))
#price
#rating

#rating = soup.find("li",attrs={"class":"col-xs-6 col-sm-4 col-md-3 col-lg-3"}).find("p")["class"][1]+" Stars"
#rating
#genre
#genre = soup2.find_all("li")[2].get_text().strip()
#genre
#availability
#availability = soup.find("li",attrs={"class":"col-xs-6 col-sm-4 col-md-3 col-lg-3"}).find_all("p", {"class": "instock availability"})[0].get_text().strip()
#availability

50

In [ ]:
import requests
from bs4 import BeautifulSoup
import math

url_initial = "https://books.toscrape.com/"
url_cat = "https://books.toscrape.com/catalogue/"
#len(book_grid)

def scrape_books (min_rating,max_price):

    response0 = requests.get(url_initial)
    soup0=BeautifulSoup(response0.content)

    total_pages = math.ceil(int(soup0.find("form", attrs = {"class":"form-horizontal"}).find_all("strong")[0].get_text())/int(soup0.find("form", attrs = {"class":"form-horizontal"}).find_all("strong")[2].get_text()))
    display(total_pages)
    my_dict = {}
    key = 0

    for page in range(1, total_pages+1):

        url = f"https://books.toscrape.com/catalogue/page-{page}.html"

        response = requests.get(url)
        response.content
        soup=BeautifulSoup(response.content)
        per_page = int(soup.find("form", attrs = {"class":"form-horizontal"}).find_all("strong")[2].get_text())
        display(per_page)
        product_grid = soup.find("div",{"class":"col-sm-8 col-md-9"})
        products = product_grid.find_all("li",{"class":"col-xs-6 col-sm-4 col-md-3 col-lg-3"})
        
        for prod in products:
            
            product_url = url_cat+prod.find("a")["href"]
            print(key)
            response2 = requests.get(product_url)
            soup2=BeautifulSoup(response2.content)
            price = float(prod.find("div",attrs={"class":"product_price"}).find("p",attrs={"class":"price_color"}).get_text().replace("£",""))
            rating = prod.find("p")["class"][1]
            r_dict = {"Zero":0,
                        "One":1,
                        "Two":2,
                        "Three":3,
                        "Four":4,
                        "Five":5}
            rate = int(r_dict[rating])

            if price <= max_price and rate >= min_rating:
                my_dict[key] = {
                            "upc" : soup2.find("table", {"class":"table table-striped"}).find("tr").find("td").get_text(),
                            "title" : prod.find_all("a")[1].get_text(),
                            "price" : price,
                            "rating" : rating,
                            "genre" : soup2.find_all("li")[2].get_text().strip(),
                            "availability" : prod.find_all("p", {"class": "instock availability"})[0].get_text().strip()
                }
            key += 1
        import pandas as pd
        df = pd.DataFrame.from_dict(my_dict, orient="index")
    return df
    
df

scrape_books (4,20.00)

,upc,title,price,rating,genre,availability
12,ce6396b0f23f6ecc,Set Me Free,17.46,Five,Young Adult,In stock
30,6258a1f6a6dcfe50,The Four Agreements: A ...,17.66,Five,Spirituality,In stock
34,6be3beb0793a53e7,Sophie's World,15.94,Five,Philosophy,In stock
47,657fe5ead67a7767,Untitled Collection: Sabbath Poems ...,14.27,Four,Poetry,In stock
53,51653ef291ab7ddc,This One Summer,19.49,Four,Sequential Art,In stock
...,...,...,...,...,...,...
913,9c96cd1329fbd82d,The Zombie Room,19.69,Five,Default,In stock
917,b78deb463531d078,The Silent Wife,12.34,Five,Fiction,In stock
934,4280ac3eab57aa5d,The Girl You Lost,12.29,Five,Mystery,In stock
937,29fc016c459aeb14,The Edge of Reason ...,19.18,Four,Womens Fiction,In stock
997,19fec36a1dfb4c16,A Spy's Devotion (The ...,16.97,Five,Historical Fiction,In stock

In [11]:
p = df.pivot_table(index="rating", columns="availability", values="price", aggfunc="mean")
p

availability   In stock
rating
Five          14.564286
Four          14.579394