# Lab | Web Scraping

Welcome to the "Books to Scrape" Web Scraping Adventure Lab!

**Objective**

In this lab, we will embark on a mission to unearth valuable insights from the data available on Books to Scrape, an online platform showcasing a wide variety of books. As data analyst, you have been tasked with scraping a specific subset of book data from Books to Scrape to assist publishing companies in understanding the landscape of highly-rated books across different genres. Your insights will help shape future book marketing strategies and publishing decisions.

**Background**

In a world where data has become the new currency, businesses are leveraging big data to make informed decisions that drive success and profitability. The publishing industry, much like others, utilizes data analytics to understand market trends, reader preferences, and the performance of books based on factors such as genre, author, and ratings. Books to Scrape serves as a rich source of such data, offering detailed information about a diverse range of books, making it an ideal platform for extracting insights to aid in informed decision-making within the literary world.

**Task**

Your task is to create a Python script using BeautifulSoup and pandas to scrape Books to Scrape book data, focusing on book ratings and genres. The script should be able to filter books with ratings above a certain threshold and in specific genres. Additionally, the script should structure the scraped data in a tabular format using pandas for further analysis.

**Expected Outcome**

A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`. The function should scrape book data from the "Books to Scrape" website and return a `pandas` DataFrame with the following columns:

**Expected Outcome**

- A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`.
- The function should return a DataFrame with the following columns:
  - **UPC**: The Universal Product Code (UPC) of the book.
  - **Title**: The title of the book.
  - **Price (£)**: The price of the book in pounds.
  - **Rating**: The rating of the book (1-5 stars).
  - **Genre**: The genre of the book.
  - **Availability**: Whether the book is in stock or not.
  - **Description**: A brief description or product description of the book (if available).
  
You will execute this script to scrape data for books with a minimum rating of `4.0 and above` and a maximum price of `£20`. 

Remember to experiment with different ratings and prices to ensure your code is versatile and can handle various searches effectively!

**Resources**

- [Beautiful Soup Documentation](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)
- [Pandas Documentation](https://pandas.pydata.org/pandas-docs/stable/index.html)
- [Books to Scrape](https://books.toscrape.com/)

**Hint**

Your first mission is to familiarize yourself with the **Books to Scrape** website. Navigate to [Books to Scrape](http://books.toscrape.com/) and explore the available books to understand their layout and structure. 

Next, think about how you can set parameters for your data extraction:

- **Minimum Rating**: Focus on books with a rating of 4.0 and above.
- **Maximum Price**: Filter for books priced up to £20.

After reviewing the site, you can construct a plan for scraping relevant data. Pay attention to the details displayed for each book, including the title, price, rating, and availability. This will help you identify the correct HTML elements to target with your scraping script.

Make sure to build your scraping URL and logic based on the patterns you observe in the HTML structure of the book listings!


---

**Best of luck! Immerse yourself in the world of books, and may the data be with you!**

**Important Note**:

In the fast-changing online world, websites often update and change their structures. When you try this lab, the **Books to Scrape** website might differ from what you expect.

If you encounter issues due to these changes, like new rules or obstacles preventing data extraction, don’t worry! Get creative.

You can choose another website that interests you and is suitable for scraping data. Options like Wikipedia, The New York Times, or even library databases are great alternatives. The main goal remains the same: extract useful data and enhance your web scraping skills while exploring a source of information you enjoy. This is your opportunity to practice and adapt to different web environments!

In [ ]:
# Your solution goes here. UPC/Title/Price/rating/Genre/availability/description; min 4.0 and above mx price 20

#response = requests.get(url_initial)
#response.content
#soup=BeautifulSoup(response.content)
#total_pages = math.ceil(int(soup.find("form", attrs = {"class":"form-horizontal"}).find_all("strong")[0].get_text())/int(soup.find("form", attrs = {"class":"form-horizontal"}).find_all("strong")[2].get_text()))
#total_pages

#product URL
#product_grid = soup.find("div",{"class":"col-sm-8 col-md-9"})
#products = product_grid.find_all("li",{"class":"col-xs-6 col-sm-4 col-md-3 col-lg-3"})
#display(products)[0]
#display(len(products))
#product_url = url_initial+product_grid.find("a")["href"]
#product_url


#UPC
#response2 = requests.get(product_url)
#response2.content
#soup2=BeautifulSoup(response2.content)
#soup2
#upc = soup2.find("table", {"class":"table table-striped"}).find("tr").find("td").get_text()
#display(upc)

#title
#itle = soup.find("li",attrs={"class":"col-xs-6 col-sm-4 col-md-3 col-lg-3"}).find_all("a")[1].get_text()
#title


#price

#price = float(soup.find("div",attrs={"class":"product_price"}).find("p",attrs={"class":"price_color"}).get_text().replace("£",""))
#price
#rating

#rating = soup.find("li",attrs={"class":"col-xs-6 col-sm-4 col-md-3 col-lg-3"}).find("p")["class"][1]+" Stars"
#rating
#genre
#genre = soup2.find_all("li")[2].get_text().strip()
#genre
#availability
#availability = soup.find("li",attrs={"class":"col-xs-6 col-sm-4 col-md-3 col-lg-3"}).find_all("p", {"class": "instock availability"})[0].get_text().strip()
#availability

50

In [ ]:
import requests
from bs4 import BeautifulSoup
import math

url_initial = "https://books.toscrape.com/"
url_cat = "https://books.toscrape.com/catalogue/"
#len(book_grid)

def scrape_books (min_rating,max_price):

    response0 = requests.get(url_initial)
    soup0=BeautifulSoup(response0.content)

    total_pages = math.ceil(int(soup0.find("form", attrs = {"class":"form-horizontal"}).find_all("strong")[0].get_text())/int(soup0.find("form", attrs = {"class":"form-horizontal"}).find_all("strong")[2].get_text()))
    display(total_pages)
    my_dict = {}
    key = 0

    for page in range(1, total_pages+1):

        url = f"https://books.toscrape.com/catalogue/page-{page}.html"

        response = requests.get(url)
        response.content
        soup=BeautifulSoup(response.content)
        per_page = int(soup.find("form", attrs = {"class":"form-horizontal"}).find_all("strong")[2].get_text())
        display(per_page)
        product_grid = soup.find("div",{"class":"col-sm-8 col-md-9"})
        products = product_grid.find_all("li",{"class":"col-xs-6 col-sm-4 col-md-3 col-lg-3"})
        
        for prod in products:
            
            product_url = url_cat+prod.find("a")["href"]
            print(key)
            response2 = requests.get(product_url)
            soup2=BeautifulSoup(response2.content)
            price = float(prod.find("div",attrs={"class":"product_price"}).find("p",attrs={"class":"price_color"}).get_text().replace("£",""))
            rating = prod.find("p")["class"][1]
            r_dict = {"Zero":0,
                        "One":1,
                        "Two":2,
                        "Three":3,
                        "Four":4,
                        "Five":5}
            rate = int(r_dict[rating])

            if price <= max_price and rate >= min_rating:
                my_dict[key] = {
                            "upc" : soup2.find("table", {"class":"table table-striped"}).find("tr").find("td").get_text(),
                            "title" : prod.find_all("a")[1].get_text(),
                            "price" : price,
                            "rating" : rating,
                            "genre" : soup2.find_all("li")[2].get_text().strip(),
                            "availability" : prod.find_all("p", {"class": "instock availability"})[0].get_text().strip(),
                            "description" : soup2.find("article", {"class":"product_page"}).find_all("p")[3].get_text().strip()
                }
            key += 1
        import pandas as pd
        df = pd.DataFrame.from_dict(my_dict, orient="index")
    return df
    
df

scrape_books (4,20.00)

50

20

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19

40

20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39

60

40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59

80

60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79

100

80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99

120

100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119

140

120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139

160

140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159

180

160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179

200

180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199

220

200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219

240

220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239

260

240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259

280

260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279

300

280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299

320

300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319

340

320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339

360

340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359

380

360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379

400

380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399

420

400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419

440

420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439

460

440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459

480

460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479

500

480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499

520

500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519

540

520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539

560

540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559

580

560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579

600

580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599

620

600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619

640

620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639

660

640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659

680

660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679

700

680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699

720

700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719

740

720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739

760

740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759

780

760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779

800

780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799

820

800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819

840

820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839

860

840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859

880

860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879

900

880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899

920

900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919

940

920
921
922
923
924
925
926
927
928
929
930
931
932
933
934
935
936
937
938
939

960

940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959

980

960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979

1000

980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999

,upc,title,price,rating,genre,availability,description
12,ce6396b0f23f6ecc,Set Me Free,17.46,Five,Young Adult,In stock,£17.46
30,6258a1f6a6dcfe50,The Four Agreements: A ...,17.66,Five,Spirituality,In stock,£17.66
34,6be3beb0793a53e7,Sophie's World,15.94,Five,Philosophy,In stock,£15.94
47,657fe5ead67a7767,Untitled Collection: Sabbath Poems ...,14.27,Four,Poetry,In stock,£14.27
53,51653ef291ab7ddc,This One Summer,19.49,Four,Sequential Art,In stock,£19.49
...,...,...,...,...,...,...,...
913,9c96cd1329fbd82d,The Zombie Room,19.69,Five,Default,In stock,£19.69
917,b78deb463531d078,The Silent Wife,12.34,Five,Fiction,In stock,£12.34
934,4280ac3eab57aa5d,The Girl You Lost,12.29,Five,Mystery,In stock,£12.29
937,29fc016c459aeb14,The Edge of Reason ...,19.18,Four,Womens Fiction,In stock,£19.18
997,19fec36a1dfb4c16,A Spy's Devotion (The ...,16.97,Five,Historical Fiction,In stock,£16.97

In [11]:
p = df.pivot_table(index="rating", columns="availability", values="price", aggfunc="mean")
p

availability   In stock
rating
Five          14.564286
Four          14.579394