# Lab | Web Scraping

Welcome to the "Books to Scrape" Web Scraping Adventure Lab!

**Objective**

In this lab, we will embark on a mission to unearth valuable insights from the data available on Books to Scrape, an online platform showcasing a wide variety of books. As data analyst, you have been tasked with scraping a specific subset of book data from Books to Scrape to assist publishing companies in understanding the landscape of highly-rated books across different genres. Your insights will help shape future book marketing strategies and publishing decisions.

**Background**

In a world where data has become the new currency, businesses are leveraging big data to make informed decisions that drive success and profitability. The publishing industry, much like others, utilizes data analytics to understand market trends, reader preferences, and the performance of books based on factors such as genre, author, and ratings. Books to Scrape serves as a rich source of such data, offering detailed information about a diverse range of books, making it an ideal platform for extracting insights to aid in informed decision-making within the literary world.

**Task**

Your task is to create a Python script using BeautifulSoup and pandas to scrape Books to Scrape book data, focusing on book ratings and genres. The script should be able to filter books with ratings above a certain threshold and in specific genres. Additionally, the script should structure the scraped data in a tabular format using pandas for further analysis.

**Expected Outcome**

A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`. The function should scrape book data from the "Books to Scrape" website and return a `pandas` DataFrame with the following columns:

**Expected Outcome**

- A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`.
- The function should return a DataFrame with the following columns:
  - **UPC**: The Universal Product Code (UPC) of the book.
  - **Title**: The title of the book.
  - **Price (£)**: The price of the book in pounds.
  - **Rating**: The rating of the book (1-5 stars).
  - **Genre**: The genre of the book.
  - **Availability**: Whether the book is in stock or not.
  - **Description**: A brief description or product description of the book (if available).
  
You will execute this script to scrape data for books with a minimum rating of `4.0 and above` and a maximum price of `£20`. 

Remember to experiment with different ratings and prices to ensure your code is versatile and can handle various searches effectively!

**Resources**

- [Beautiful Soup Documentation](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)
- [Pandas Documentation](https://pandas.pydata.org/pandas-docs/stable/index.html)
- [Books to Scrape](https://books.toscrape.com/)

**Hint**

Your first mission is to familiarize yourself with the **Books to Scrape** website. Navigate to [Books to Scrape](http://books.toscrape.com/) and explore the available books to understand their layout and structure. 

Next, think about how you can set parameters for your data extraction:

- **Minimum Rating**: Focus on books with a rating of 4.0 and above.
- **Maximum Price**: Filter for books priced up to £20.

After reviewing the site, you can construct a plan for scraping relevant data. Pay attention to the details displayed for each book, including the title, price, rating, and availability. This will help you identify the correct HTML elements to target with your scraping script.

Make sure to build your scraping URL and logic based on the patterns you observe in the HTML structure of the book listings!


---

**Best of luck! Immerse yourself in the world of books, and may the data be with you!**

**Important Note**:

In the fast-changing online world, websites often update and change their structures. When you try this lab, the **Books to Scrape** website might differ from what you expect.

If you encounter issues due to these changes, like new rules or obstacles preventing data extraction, don’t worry! Get creative.

You can choose another website that interests you and is suitable for scraping data. Options like Wikipedia, The New York Times, or even library databases are great alternatives. The main goal remains the same: extract useful data and enhance your web scraping skills while exploring a source of information you enjoy. This is your opportunity to practice and adapt to different web environments!

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

url = "https://books.toscrape.com/catalogue/page-1.html"

response = requests.get(url)
print(response.status_code)

200

I am starting with only the first page. When I get everything I'll try to iterate over the pages as well and get all the information.

In [ ]:
soup = BeautifulSoup(response.content, "html.parser")
print(soup.prettify())

In [ ]:
soup.find_all("h3")

In [ ]:
soup.find("h3").find("a")["title"]

# I know how to get a title, now I have to try to iterate and get all of them.

In [ ]:
titles = []

for title in soup.find_all("h3"):
    titles.append(title.find("a")["title"])

titles

I've just realized that some information is in the page of the books themselves. E.g. you cannot scrape the UPC from the outside. I'll start from the beginning. I'm going to scrap all the information from one book, then I'll use iterations to get information from the rest.

In [2]:
urlbook = "https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html"

response = requests.get(urlbook)
print(response.status_code)

200

In [3]:
soup = BeautifulSoup(response.content, "html.parser")
print(soup.prettify())

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en-us">
 <!--<![endif]-->
 <head>
  <title>
   A Light in the Attic | Books to Scrape - Sandbox
  </title>
  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>
  <meta content="24th Jun 2016 09:29" name="created"/>
  <meta content="
    It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love th It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love that Silverstein. Need proof of his genius? RockabyeRockabye baby, in the treetopDon't you know a treetopIs no safe place to rock?And who put you up there,And your cradle, too?Baby, I think someone down here'sGot it in for you. Shel, you never sounded so good. ...more
" name="description"/>
  <meta content="width=device-width" name="viewport"/>
  <meta content="NOARCHIVE,NOCACHE" name="robots"/>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
  <link href="../../static/oscar/favicon.ico" rel="shortcut icon"/>
  <link href="../../static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>
  <link href="../../static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>
  <link href="../../static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>
 </head>
 <body class="default" id="default">
  <header class="header container-fluid">
   <div class="page_inner">
    <div class="row">
     <div class="col-sm-8 h1">
      <a href="../../index.html">
       Books to Scrape
      </a>
      <small>
       We love being scraped!
      </small>
     </div>
    </div>
   </div>
  </header>
  <div class="container-fluid page">
   <div class="page_inner">
    <ul class="breadcrumb">
     <li>
      <a href="../../index.html">
       Home
      </a>
     </li>
     <li>
      <a href="../category/books_1/index.html">
       Books
      </a>
     </li>
     <li>
      <a href="../category/books/poetry_23/index.html">
       Poetry
      </a>
     </li>
     <li class="active">
      A Light in the Attic
     </li>
    </ul>
    <div id="messages">
    </div>
    <div class="content">
     <div id="promotions">
     </div>
     <div id="content_inner">
      <article class="product_page">
       <!-- Start of product page -->
       <div class="row">
        <div class="col-sm-6">
         <div class="carousel" id="product_gallery">
          <div class="thumbnail">
           <div class="carousel-inner">
            <div class="item active">
             <img alt="A Light in the Attic" src="../../media/cache/fe/72/fe72f0532301ec28892ae79a629a293c.jpg"/>
            </div>
           </div>
          </div>
         </div>
        </div>
        <div class="col-sm-6 product_main">
         <h1>
          A Light in the Attic
         </h1>
         <p class="price_color">
          £51.77
         </p>
         <p class="instock availability">
          <i class="icon-ok">
          </i>
          In stock (22 available)
         </p>
         <p class="star-rating Three">
          <i class="icon-star">
          </i>
          <i class="icon-star">
          </i>
          <i class="icon-star">
          </i>
          <i class="icon-star">
          </i>
          <i class="icon-star">
          </i>
          <!-- <small><a href="/catalogue/a-light-in-the-attic_1000/reviews/">


                    0 customer reviews

        </a></small>
         -->
          <!--
    <a id="write_review" href="/catalogue/a-light-in-the-attic_1000/reviews/add/#addreview" class="btn btn-success btn-sm">
        Write a review
    </a>

 -->
         </p>
         <hr/>
         <div class="alert alert-warning" role="alert">
          <strong>
           Warning!
          </strong>
          This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.
         </div>
        </div>
        <!-- /col-sm-6 -->
       </div>
       <!-- /row -->
       <div class="sub-header" id="product_description">
        <h2>
         Product Description
        </h2>
       </div>
       <p>
        It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love th It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love that Silverstein. Need proof of his genius? RockabyeRockabye baby, in the treetopDon't you know a treetopIs no safe place to rock?And who put you up there,And your cradle, too?Baby, I think someone down here'sGot it in for you. Shel, you never sounded so good. ...more
       </p>
       <div class="sub-header">
        <h2>
         Product Information
        </h2>
       </div>
       <table class="table table-striped">
        <tr>
         <th>
          UPC
         </th>
         <td>
          a897fe39b1053632
         </td>
        </tr>
        <tr>
         <th>
          Product Type
         </th>
         <td>
          Books
         </td>
        </tr>
        <tr>
         <th>
          Price (excl. tax)
         </th>
         <td>
          £51.77
         </td>
        </tr>
        <tr>
         <th>
          Price (incl. tax)
         </th>
         <td>
          £51.77
         </td>
        </tr>
        <tr>
         <th>
          Tax
         </th>
         <td>
          £0.00
         </td>
        </tr>
        <tr>
         <th>
          Availability
         </th>
         <td>
          In stock (22 available)
         </td>
        </tr>
        <tr>
         <th>
          Number of reviews
         </th>
         <td>
          0
         </td>
        </tr>
       </table>
       <section>
        <div class="sub-header" id="reviews">
        </div>
       </section>
      </article>
      <!-- End of product page -->
     </div>
    </div>
   </div>
  </div>
  <footer class="footer container-fluid">
  </footer>
  <!-- jQuery -->
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js">
  </script>
  <script>
   window.jQuery || document.write('<script src="../../static/oscar/js/jquery/jquery-1.9.1.min.js"><\/script>')
  </script>
  <!-- Twitter Bootstrap -->
  <script src="../../static/oscar/js/bootstrap3/bootstrap.min.js" type="text/javascript">
  </script>
  <!-- Oscar -->
  <script charset="utf-8" src="../../static/oscar/js/oscar/ui.js" type="text/javascript">
  </script>
  <script charset="utf-8" src="../../static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.js" type="text/javascript">
  </script>
  <script charset="utf-8" src="../../static/oscar/js/bootstrap-datetimepicker/locales/bootstrap-datetimepicker.all.js" type="text/javascript">
  </script>
  <script type="text/javascript">
   $(function() {


    oscar.init();

            });
  </script>
  <!-- Version: N/A -->
 </body>
</html>

In [ ]:
print(soup.find("h1").get_text())
print(soup.find("p", class_= "price_color").text)
print(soup.find("p", class_="star-rating")["class"][1])
print(soup.find_all("li")[2].text)

# print(soup.find("p", class_= "instock availability").get_text()) 
# I tried to look for the stock like that, but it displayed in a weird way

print(soup.find("body").find_all("tr")[5].find("td").text)
print(soup.find("body").find("tr").find("td").text)
print(soup.find_all("p")[3].text)

In [4]:
print(soup.find_all("li")[2].text)

Poetry

I have now the way to access every book information. Now, I'll make an iterate over the url to get information from several books.

In [ ]:
number = 1000
for page in range(0,3):
    book = titles[page].lower().replace(" ", "-")
    url = f"https://books.toscrape.com/catalogue/{book}_{number}/index.html"
    number -= 1
    print(url)

# I have the way to get all the urls i need.

In [ ]:
#titles = []

#for title in soup.find_all("h3"):
    #titles.append(title.find("a")["title"])

all_titles = []
all_prices = []
all_ratings = []
all_stocks = []
all_upc = []
all_descriptions = []
number = 1000
for i in range(0,10):
    try:
        book = titles[i].lower().replace(" ", "-")
        url = f"https://books.toscrape.com/catalogue/{book}_{number}/index.html"
        number -= 1
        response = requests.get(url)
        soup = BeautifulSoup(response.content, "html.parser")
        print("Working on...", titles[i])
        all_titles.append(soup.find("h1").get_text())
        all_prices.append(soup.find("p", class_= "price_color").text)
        all_ratings.append(soup.find("p", class_="star-rating")["class"][1])
        all_stocks.append(soup.find("body").find_all("tr")[5].find("td").text)
        all_upc.append(soup.find("body").find("tr").find("td").text)
        all_descriptions.append(soup.find_all("p")[3].text)
        time.sleep(5)
    #except:
        #pass
    except Exception as e:
        print(e)

pd.DataFrame({"UPC" : all_upc,
              "title" : all_titles,
              "prices" : all_prices,
              "ratings" : all_ratings,
              "stock" : all_stocks, 
              "description" : all_descriptions})
#print (len(all_titles), len(all_prices), len(all_ratings), len(all_stocks), len(all_upc), len(all_descriptions))

# I was trying but something was wrong. I decided to tidy a little bit the code. 
# In the next code cell, I've tried to organize the different stages into functions.
# And I've been working on solving the errors.

In [40]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def get_titles():
    titles = []
    for number in range (1,51):
        try:
            url = f"https://books.toscrape.com/catalogue/page-{number}.html"
            response = requests.get(url)
            soup = BeautifulSoup(response.content, "html.parser")
            #time.sleep(1)
            for title in soup.find_all("h3"):
                titles.append(title.find("a")["title"])
        except Exception as e:
            print(e)
    return titles

def get_url(titles, number = 1000):
    urls = []  
    for i in range(0,len(titles)):
        book = (titles[i].lower().replace(" ", "-")
            .replace(":", "")
            .replace("(", "")
            .replace(")","")
            .replace("#","")
            .replace(",","")
            .replace("'","")
            .replace("*","")
            .replace('"',"")
            .replace("´","")
            .replace(".","")
            .replace("[","")
            .replace("]","")
            .replace("“","")
            .replace("”",""))
        url = f"https://books.toscrape.com/catalogue/{book}_{number}/index.html"
        number -= 1
        urls.append(url)
    return urls

def make_df(urls, min_rating, max_price):
    all_titles = []
    all_prices = []
    all_ratings = []
    all_genres = []
    all_stocks = []
    all_upc = []
    all_descriptions = []
    
    for url in urls:
        try:
            response = requests.get(url)
            soup = BeautifulSoup(response.content, "html.parser")
            #print("Working on...", url)
            #time.sleep(3)
            rating_map = {"One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5}
            rating = rating_map[(soup.find("p", class_="star-rating")["class"][1])]
            price = float(soup.find("p", class_= "price_color").text.lstrip("£"))
            if rating >= min_rating and price <= max_price:
                all_titles.append(soup.find("h1").get_text())
                all_prices.append(soup.find("p", class_= "price_color").text)
                all_ratings.append(rating)
                all_genres.append(soup.find_all("li")[2].text.strip("\n"))
                all_stocks.append(soup.find("body").find_all("tr")[5].find("td").text)
                all_upc.append(soup.find("body").find("tr").find("td").text)
                all_descriptions.append(soup.find_all("p")[3].text)
        #except:
            #pass
        except Exception as e:
            print(url, e)
    
    df = pd.DataFrame({"UPC" : all_upc,
                  "title" : all_titles,
                  "prices" : all_prices,
                  "ratings" : all_ratings,
                    "genres" : all_genres,
                  "stock" : all_stocks, 
                  "description" : all_descriptions})
    return df

def scrape_books(min_rating, max_price):
    titles = get_titles()
    urls = get_url(titles)
    df = make_df(urls, min_rating, max_price)
    return df

# I think this would work amazingly, but I would have to waste a huge amount of time trying. so i'm going to simplify it a little bit to test it
# this works, but I'm scraping too much webpages just for a lab. I'm going to duplicate the code, scrape just the first page and test it.

In [15]:
def make_df(urls, min_rating, max_price):
    all_titles = []
    all_prices = []
    all_ratings = []
    all_genres = []
    all_stocks = []
    all_upc = []
    all_descriptions = []
    
    for url in urls:
        try:
            response = requests.get(url)
            soup = BeautifulSoup(response.content, "html.parser")
            time.sleep(3)
            rating_map = {"One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5}
            rating = rating_map[(soup.find("p", class_="star-rating")["class"][1])]
            price = float(soup.find("p", class_= "price_color").text.lstrip("£"))
            if rating >= min_rating and price <= max_price:
                print("Working on...", url)
                all_titles.append(soup.find("h1").get_text())
                all_prices.append(soup.find("p", class_= "price_color").text)
                all_ratings.append(rating)
                all_genres.append(soup.find_all("li")[2].text.strip("\n"))
                all_stocks.append(soup.find("body").find_all("tr")[5].find("td").text)
                all_upc.append(soup.find("body").find("tr").find("td").text)
                all_descriptions.append(soup.find_all("p")[3].text)
        #except:
            #pass
        except Exception as e:
            print(e)
    
    df = pd.DataFrame({"UPC" : all_upc,
                  "title" : all_titles,
                  "prices" : all_prices,
                  "ratings" : all_ratings,
                    "genres" : all_genres,
                  "stock" : all_stocks, 
                  "description" : all_descriptions})
    return df

# I've trying and working on this function. Now, it works and I pasted it in the previous code cell.

In [18]:
make_df(["https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html"], 3, 200)

Working on... https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html

,UPC,title,prices,ratings,genres,stock,description
0,a897fe39b1053632,A Light in the Attic,£51.77,3,\nPoetry\n,In stock (22 available),It's hard to imagine a world without A Light i...

In [50]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

def get_titles():
    titles = []
    for number in range (1,4):
        try:
            url = f"https://books.toscrape.com/catalogue/page-{number}.html"
            response = requests.get(url)
            soup = BeautifulSoup(response.content, "html.parser")
            time.sleep(1)
            for title in soup.find_all("h3"):
                titles.append(title.find("a")["title"])
        except Exception as e:
            print(e)
    return titles

def get_url(titles, number = 1000):
    urls = []  
    for i in range(0,len(titles)):
        book = (titles[i].lower()
            .replace(":", "")
            .replace("(", "")
            .replace(")","")
            .replace("#","")
            .replace(",","")
            .replace("'","")
            .replace("*","")
            .replace('"',"")
            .replace("´","")
            .replace(".","")
            .replace("[","")
            .replace("]","")
            .replace("“","")
            .replace("”","")
            .replace("!","")
            .replace("?","")
            .replace("&","")
            .replace(" ", "-"))
        url = f"https://books.toscrape.com/catalogue/{book}_{number}/index.html"
        number -= 1
        urls.append(url)
    return urls

def make_df(urls, min_rating, max_price):
    all_titles = []
    all_prices = []
    all_ratings = []
    all_genres = []
    all_stocks = []
    all_upc = []
    all_descriptions = []
    
    for url in urls:
        try:
            response = requests.get(url)
            soup = BeautifulSoup(response.content, "html.parser")
            print("Working on...", url)
            time.sleep(3)
            rating_map = {"One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5}
            rating = rating_map[(soup.find("p", class_="star-rating")["class"][1])]
            price = float(soup.find("p", class_= "price_color").text.lstrip("£"))
            if rating >= min_rating and price <= max_price:
                all_titles.append(soup.find("h1").get_text())
                all_prices.append(soup.find("p", class_= "price_color").text)
                all_ratings.append(rating)
                all_genres.append(soup.find_all("li")[2].text.strip("\n"))
                all_stocks.append(soup.find("body").find_all("tr")[5].find("td").text)
                all_upc.append(soup.find("body").find("tr").find("td").text)
                all_descriptions.append(soup.find_all("p")[3].text)
        #except:
            #pass
        except Exception as e:
            print(url, e)
    
    df = pd.DataFrame({"UPC" : all_upc,
                  "title" : all_titles,
                  "prices" : all_prices,
                  "ratings" : all_ratings,
                    "genres" : all_genres,
                  "stock" : all_stocks, 
                  "description" : all_descriptions})
    return df

def scrape_books(min_rating, max_price):
    titles = get_titles()
    urls = get_url(titles)
    df = make_df(urls, min_rating, max_price)
    return df

# I got it working in the end.

In [51]:
#I´m scrapping the three first pages of the web
df = scrape_books (4, 20)

Working on... https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html
Working on... https://books.toscrape.com/catalogue/tipping-the-velvet_999/index.html
Working on... https://books.toscrape.com/catalogue/soumission_998/index.html
Working on... https://books.toscrape.com/catalogue/sharp-objects_997/index.html
Working on... https://books.toscrape.com/catalogue/sapiens-a-brief-history-of-humankind_996/index.html
Working on... https://books.toscrape.com/catalogue/the-requiem-red_995/index.html
Working on... https://books.toscrape.com/catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html
Working on... https://books.toscrape.com/catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html
Working on... https://books.toscrape.com/catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html
Working on... https://books.toscrape.com/catalogue/the-black-maria_991/index.html
Working on... https://books.toscrape.com/catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html
Working on... https://books.toscrape.com/catalogue/shakespeares-sonnets_989/index.html
Working on... https://books.toscrape.com/catalogue/set-me-free_988/index.html
Working on... https://books.toscrape.com/catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html
Working on... https://books.toscrape.com/catalogue/rip-it-up-and-start-again_986/index.html
Working on... https://books.toscrape.com/catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html
Working on... https://books.toscrape.com/catalogue/olio_984/index.html
Working on... https://books.toscrape.com/catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html
Working on... https://books.toscrape.com/catalogue/libertarianism-for-beginners_982/index.html
Working on... https://books.toscrape.com/catalogue/its-only-the-himalayas_981/index.html
Working on... https://books.toscrape.com/catalogue/in-her-wake_980/index.html
Working on... https://books.toscrape.com/catalogue/how-music-works_979/index.html
Working on... https://books.toscrape.com/catalogue/foolproof-preserving-a-guide-to-small-batch-jams-jellies-pickles-condiments-and-more-a-foolproof-guide-to-making-small-batch-jams-jellies-pickles-condiments-and-more_978/index.html
Working on... https://books.toscrape.com/catalogue/chase-me-paris-nights-2_977/index.html
Working on... https://books.toscrape.com/catalogue/black-dust_976/index.html
Working on... https://books.toscrape.com/catalogue/birdsong-a-story-in-pictures_975/index.html
Working on... https://books.toscrape.com/catalogue/americas-cradle-of-quarterbacks-western-pennsylvanias-football-factory-from-johnny-unitas-to-joe-montana_974/index.html
Working on... https://books.toscrape.com/catalogue/aladdin-and-his-wonderful-lamp_973/index.html
Working on... https://books.toscrape.com/catalogue/worlds-elsewhere-journeys-around-shakespeare’s-globe_972/index.html
https://books.toscrape.com/catalogue/worlds-elsewhere-journeys-around-shakespeare’s-globe_972/index.html 'NoneType' object is not subscriptable
Working on... https://books.toscrape.com/catalogue/wall-and-piece_971/index.html
Working on... https://books.toscrape.com/catalogue/the-four-agreements-a-practical-guide-to-personal-freedom_970/index.html
Working on... https://books.toscrape.com/catalogue/the-five-love-languages-how-to-express-heartfelt-commitment-to-your-mate_969/index.html
Working on... https://books.toscrape.com/catalogue/the-elephant-tree_968/index.html
Working on... https://books.toscrape.com/catalogue/the-bear-and-the-piano_967/index.html
Working on... https://books.toscrape.com/catalogue/sophies-world_966/index.html
Working on... https://books.toscrape.com/catalogue/penny-maybe_965/index.html
Working on... https://books.toscrape.com/catalogue/maude-1883-1993she-grew-up-with-the-country_964/index.html
Working on... https://books.toscrape.com/catalogue/in-a-dark-dark-wood_963/index.html
Working on... https://books.toscrape.com/catalogue/behind-closed-doors_962/index.html
Working on... https://books.toscrape.com/catalogue/you-cant-bury-them-all-poems_961/index.html
Working on... https://books.toscrape.com/catalogue/slow-states-of-collapse-poems_960/index.html
Working on... https://books.toscrape.com/catalogue/reasons-to-stay-alive_959/index.html
Working on... https://books.toscrape.com/catalogue/private-paris-private-10_958/index.html
Working on... https://books.toscrape.com/catalogue/higherselfie-wake-up-your-life-free-your-soul-find-your-tribe_957/index.html
Working on... https://books.toscrape.com/catalogue/without-borders-wanderlove-1_956/index.html
Working on... https://books.toscrape.com/catalogue/when-we-collided_955/index.html
Working on... https://books.toscrape.com/catalogue/we-love-you-charlie-freeman_954/index.html
Working on... https://books.toscrape.com/catalogue/untitled-collection-sabbath-poems-2014_953/index.html
Working on... https://books.toscrape.com/catalogue/unseen-city-the-majesty-of-pigeons-the-discreet-charm-of-snails--other-wonders-of-the-urban-wilderness_952/index.html
https://books.toscrape.com/catalogue/unseen-city-the-majesty-of-pigeons-the-discreet-charm-of-snails--other-wonders-of-the-urban-wilderness_952/index.html 'NoneType' object is not subscriptable
Working on... https://books.toscrape.com/catalogue/unicorn-tracks_951/index.html
Working on... https://books.toscrape.com/catalogue/unbound-how-eight-technologies-made-us-human-transformed-society-and-brought-our-world-to-the-brink_950/index.html
Working on... https://books.toscrape.com/catalogue/tsubasa-world-chronicle-2-tsubasa-world-chronicle-2_949/index.html
Working on... https://books.toscrape.com/catalogue/throwing-rocks-at-the-google-bus-how-growth-became-the-enemy-of-prosperity_948/index.html
Working on... https://books.toscrape.com/catalogue/this-one-summer_947/index.html
Working on... https://books.toscrape.com/catalogue/thirst_946/index.html
Working on... https://books.toscrape.com/catalogue/the-torch-is-passed-a-harding-family-story_945/index.html
Working on... https://books.toscrape.com/catalogue/the-secret-of-dreadwillow-carse_944/index.html
Working on... https://books.toscrape.com/catalogue/the-pioneer-woman-cooks-dinnertime-comfort-classics-freezer-food-16-minute-meals-and-other-delicious-ways-to-solve-supper_943/index.html
Working on... https://books.toscrape.com/catalogue/the-past-never-ends_942/index.html
Working on... https://books.toscrape.com/catalogue/the-natural-history-of-us-the-fine-art-of-pretending-2_941/index.html

In [52]:
df

,UPC,title,prices,ratings,genres,stock,description
0,ce6396b0f23f6ecc,Set Me Free,£17.46,5,Young Adult,In stock (19 available),Aaron Ledbetter’s future had been planned out ...
1,6258a1f6a6dcfe50,The Four Agreements: A Practical Guide to Pers...,£17.66,5,Spirituality,In stock (18 available),"In The Four Agreements, don Miguel Ruiz reveal..."
2,6be3beb0793a53e7,Sophie's World,£15.94,5,Philosophy,In stock (18 available),A page-turning novel that is also an explorati...
3,657fe5ead67a7767,Untitled Collection: Sabbath Poems 2014,£14.27,4,Poetry,In stock (16 available),"More than thirty-five years ago, when the weat..."
4,51653ef291ab7ddc,This One Summer,£19.49,4,Sequential Art,In stock (16 available),"Every summer, Rose goes with her mom and dad t..."
5,709822d0b5bcb7f4,Thirst,£17.27,5,Fiction,In stock (16 available),"On a searing summer Friday, Eddie Chapman has ..."